name: mango_optimizer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # PyTorch with CUDA support
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8

  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0

  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # System monitoring
  - psutil>=5.8.0

  # Development tools
  - jupyter
  - ipykernel
  - pytest>=6.2.0
  - pytest-cov>=2.12.0

  # Progress bars
  - tqdm>=4.62.0

  # Optional: memory profiling
  - memory_profiler>=0.60.0

  # GPU monitoring (optional)
  - gpustat

  # Development utilities
  - black  # Code formatting
  - flake8  # Linting
  - isort  # Import sorting